# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

f1hn = "dns1.centos64.hadoop.ianbuss.dev"
f1ip  = "192.168.51.30"
f1ip2 = "192.168.52.30"
f2hn = "dns2.centos64.hadoop.ianbuss.dev"
f2ip = "192.168.51.31"
f3hn = "dns3.centos64.hadoop.ianbuss.dev"
f3ip = "192.168.52.31"
f4hn = "client.centos64.hadoop.ianbuss.dev"
f4ip  = "192.168.51.32"
f4ip2 = "192.168.52.32"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "centos65-large"
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  # Dual box
  config.vm.define "f1" do |f1|
    f1.vm.network :private_network, ip: f1ip
    f1.vm.network :private_network, ip: f1ip2
    f1.vm.hostname = f1hn
    f1.vm.provision :shell do |s|
      s.path = "../provisioning/centos-hostname.sh"
      s.args = [f1hn, f1ip]
    end
  end

  # 51 node
  config.vm.define "f2" do |f2|
    f2.vm.network :private_network, ip: f2ip
    f2.vm.hostname = f2hn
    f2.vm.provision :shell do |s|
      s.path = "../provisioning/centos-hostname.sh"
      s.args = [f2hn, f2ip]
    end
  end

  # 52 node
  config.vm.define "f3" do |f3|
    f3.vm.network :private_network, ip: f3ip
    f3.vm.hostname = f3hn
    f3.vm.provision :shell do |s|
      s.path = "../provisioning/centos-hostname.sh"
      s.args = [f3hn, f3ip]
    end
  end

  # Client node
  config.vm.define "f4" do |f4|
    f4.vm.network :private_network, ip: f4ip
    f4.vm.network :private_network, ip: f4ip2
    f4.vm.hostname = f4hn
    f4.vm.provision :shell do |s|
      s.path = "../provisioning/centos-hostname.sh"
      s.args = [f4hn, f4ip]
    end
  end

end
