# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

ip = "192.168.153.26"
hn = "cdh52.hadoop.dev"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos65"
  config.vm.hostname = hn

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "10240"]
    vb.customize ["modifyvm", :id, "--cpus", "8"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network :private_network, ip: ip

  config.vm.provision :shell do |s|
    s.path = "../provisioning/centos-hostname.sh"
	s.args = [hn, ip]
  end
  config.vm.provision :shell do |s|
    s.path = "../provisioning/centos-yum.sh"
  end
end
